-- MySQL Script generated by MySQL Workbench
-- Tue Sep  9 10:00:21 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tarea2
-- -----------------------------------------------------

DROP SCHEMA IF EXISTS `tarea2` ;

-- -----------------------------------------------------
-- Schema tarea2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tarea2` DEFAULT CHARACTER SET utf8 ;
USE `tarea2` ;

-- -----------------------------------------------------
-- Table `tarea2`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarea2`.`region` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tarea2`.`comuna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarea2`.`comuna` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  `region_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comuna_region1_idx` (`region_id` ASC),
  CONSTRAINT `fk_comuna_region1`
    FOREIGN KEY (`region_id`)
    REFERENCES `tarea2`.`region` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tarea2`.`aviso_adopcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarea2`.`aviso_adopcion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_ingreso` DATETIME NOT NULL,
  `comuna_id` INT NOT NULL,
  `sector` VARCHAR(100) NULL,
  `nombre` VARCHAR(200) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `celular` VARCHAR(15) NULL,
  `tipo` ENUM('gato', 'perro') NOT NULL,
  `cantidad` INT NOT NULL,
  `edad` INT NOT NULL,
  `unidad_medida` ENUM('a', 'm') NOT NULL,
  `fecha_entrega` DATETIME NOT NULL,
  `descripcion` TEXT(500) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_aviso_comuna1_idx` (`comuna_id` ASC),
  CONSTRAINT `fk_aviso_comuna1`
    FOREIGN KEY (`comuna_id`)
    REFERENCES `tarea2`.`comuna` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tarea2`.`foto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarea2`.`foto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ruta_archivo` VARCHAR(300) NOT NULL,
  `nombre_archivo` VARCHAR(300) NOT NULL,
  `aviso_id` INT NOT NULL,
  PRIMARY KEY (`id`, `aviso_id`),
  INDEX `fk_foto_aviso1_idx` (`aviso_id` ASC),
  CONSTRAINT `fk_foto_aviso1`
    FOREIGN KEY (`aviso_id`)
    REFERENCES `tarea2`.`aviso_adopcion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tarea2`.`contactar_por`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tarea2`.`contactar_por` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` ENUM('whatsapp', 'telegram', 'X', 'instagram', 'tiktok', 'otra') NOT NULL,
  `identificador` VARCHAR(150) NOT NULL,
  `aviso_id` INT NOT NULL,
  PRIMARY KEY (`id`, `aviso_id`),
  INDEX `fk_contactar_por_aviso1_idx` (`aviso_id` ASC),
  CONSTRAINT `fk_contactar_por_aviso1`
    FOREIGN KEY (`aviso_id`)
    REFERENCES `tarea2`.`aviso_adopcion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO aviso_adopcion (fecha_ingreso,comuna_id,sector,nombre,email,celular,tipo,cantidad,edad,unidad_medida,fecha_entrega,descripcion) 
VALUES ("2025-08-31 14:30",130210,"Plaza Ñuñoa","Tomas","tomas@gmail.com",NULL,'perro',3,3,'m',"2025-09-01 12:00",NULL);
INSERT INTO aviso_adopcion (fecha_ingreso,comuna_id,sector,nombre,email,celular,tipo,cantidad,edad,unidad_medida,fecha_entrega,descripcion) 
VALUES ("2025-08-31 11:00",130208,"Plaza Quinta Normal","Cristian","cristian@gmail.com","+56945675319",'perro',1,3,'m',"2025-09-06 14:30",NULL);
INSERT INTO aviso_adopcion (fecha_ingreso,comuna_id,sector,nombre,email,celular,tipo,cantidad,edad,unidad_medida,fecha_entrega,descripcion) 
VALUES ("2025-08-29 12:00",130208,"Alameda con Nataniel Cox","Jackie","jackie@gmail.com",NULL,'gato',1,1,'a',"2025-09-03 12:00",NULL);
INSERT INTO aviso_adopcion (fecha_ingreso,comuna_id,sector,nombre,email,celular,tipo,cantidad,edad,unidad_medida,fecha_entrega,descripcion) 
VALUES ("2025-08-28 15:00",130202,"Villa Los Jardines","Ricardo","ricardo1@gmail.com","+56942050672",'perro',1,5,'m',"2025-08-31 14:30",NULL);
INSERT INTO aviso_adopcion (fecha_ingreso,comuna_id,sector,nombre,email,celular,tipo,cantidad,edad,unidad_medida,fecha_entrega,descripcion) 
VALUES ("2025-08-25 18:00",130208,"Beauchef 850","Sophie","sophie@gmail.com","+56912345678",'gato',1,2,'m',"2025-09-01 10:00",NULL);

INSERT INTO foto (ruta_archivo,nombre_archivo,aviso_id) VALUES ("uploads/three_dogs.png","three_dogs",1);
INSERT INTO foto (ruta_archivo,nombre_archivo,aviso_id) VALUES ("uploads/wenomechainsama.jpg","wenomechainsama",2);
INSERT INTO foto (ruta_archivo,nombre_archivo,aviso_id) VALUES ("uploads/catNC.jpg","catNC",3);
INSERT INTO foto (ruta_archivo,nombre_archivo,aviso_id) VALUES ("uploads/docky1.jpg","docky1",4);
INSERT INTO foto (ruta_archivo,nombre_archivo,aviso_id) VALUES ("uploads/docky2.jpg","docky2",4);
INSERT INTO foto (ruta_archivo,nombre_archivo,aviso_id) VALUES ("uploads/gatito-LoP.jpg","gatito-LoP",5);

INSERT INTO contactar_por (nombre,identificador,aviso_id) VALUES ('whatsapp',"+56956482491",1);
INSERT INTO contactar_por (nombre,identificador,aviso_id) VALUES ('instagram',"@W3llesJ",3);
INSERT INTO contactar_por (nombre,identificador,aviso_id) VALUES ('whatsapp',"+56942050672",4);



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
